#!/usr/bin/env python3

#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

"""Synchronize reusable Basilisk Rust build support into ``bsk-sdk``."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Sequence
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _sync_paths import SDK_REPO_ROOT, resolve_basilisk_root  # noqa: E402
from _versioning import is_publishable_bsk_version  # noqa: E402
from common import copy_file, reset_dir  # noqa: E402


SDK_RUST_ROOT = SDK_REPO_ROOT / "src" / "bsk_sdk" / "rust"

BASILISK_GIT_URL = "https://github.com/AVSLab/basilisk"
BASILISK_VERSION_FILE = Path("docs/source/bskVersion.txt")
RUST_CMAKE_FILES = (
    "bskAddRustModuleSources.cmake",
    "bskCheckRustModuleSymbols.cmake",
    "bskEnsureRustBindings.cmake",
    "bskRustSupportVersions.cmake",
)

RUST_LICENSE_FILES = (
    (
        "architecture/rust/generate_rust_licenses.py",
        "licenses/generate_rust_licenses.py",
    ),
    ("architecture/rust/licenses/about.toml", "licenses/about.toml"),
)

SUPPORT_MANIFEST_FILE = "support-manifest.txt"
SUPPORT_VERSIONS_FILE = "support-versions.json"

VERSION_VARIABLES = (
    "BSK_RUST_MIN_VERSION",
    "BSK_RUST_SUPPORT_CRATE_VERSION",
    "BSK_CORROSION_VERSION",
    "BSK_CORROSION_GIT_TAG",
)


def _support_versions(version_file: Path) -> dict[str, str]:
    """Read public Rust integration versions from the synchronized CMake file."""
    contents = version_file.read_text(encoding="utf-8")
    versions: dict[str, str] = {}
    for variable in VERSION_VARIABLES:
        match = re.search(
            rf'^set\({re.escape(variable)}\s+"([^"]+)"\)',
            contents,
            re.MULTILINE,
        )
        if match is None:
            raise RuntimeError(f"Missing {variable} in {version_file}")
        versions[variable] = match.group(1)
    return versions


def _write_support_metadata(sdk_rust_root: Path) -> None:
    """Write the installed manifest and machine-readable version metadata."""
    version_file = sdk_rust_root / "cmake" / "bskRustSupportVersions.cmake"
    versions = _support_versions(version_file)
    license_generator = sdk_rust_root / "licenses" / "generate_rust_licenses.py"
    cargo_about_match = re.search(
        r'^CARGO_ABOUT_VERSION\s*=\s*"([^"]+)"',
        license_generator.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if cargo_about_match is None:
        raise RuntimeError(f"Missing CARGO_ABOUT_VERSION in {license_generator}")
    versions["BSK_CARGO_ABOUT_VERSION"] = cargo_about_match.group(1)
    (sdk_rust_root / SUPPORT_VERSIONS_FILE).write_text(
        json.dumps(versions, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    relative_files = [
        *(Path("cmake") / filename for filename in RUST_CMAKE_FILES),
        *(Path(destination) for _, destination in RUST_LICENSE_FILES),
        Path(SUPPORT_VERSIONS_FILE),
    ]
    manifest = [
        "# Generated by tools/sync_rust.py. Do not edit.",
        *(path.as_posix() for path in relative_files),
        "",
    ]
    (sdk_rust_root / SUPPORT_MANIFEST_FILE).write_text(
        "\n".join(manifest), encoding="utf-8"
    )


def _replace_one(path: Path, pattern: str, replacement: str, description: str) -> None:
    """Replace one version field in ``path`` or fail before silently drifting."""
    contents = path.read_text(encoding="utf-8")
    updated, count = re.subn(
        pattern, replacement, contents, count=1, flags=re.MULTILINE
    )
    if count != 1:
        raise RuntimeError(f"Could not update {description} in {path}")
    path.write_text(updated, encoding="utf-8")


def _replace_dependency(
    path: Path, section: str, dependency: str, specification: str
) -> None:
    """Replace one dependency in a named TOML section without rewriting comments."""
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    current_section = ""
    replacements = 0
    dependency_re = re.compile(rf"^\s*{re.escape(dependency)}\s*=")
    newline = "\r\n" if any(line.endswith("\r\n") for line in lines) else "\n"

    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current_section = stripped
            continue
        if current_section == section and dependency_re.match(line):
            lines[index] = f"{dependency} = {specification}{newline}"
            replacements += 1

    if replacements != 1:
        raise RuntimeError(
            f"Expected one {dependency} entry in {section} of {path}; "
            f"found {replacements}"
        )
    path.write_text("".join(lines), encoding="utf-8")


def _dependency_specification(
    support_version: str,
    *,
    path: Path | None = None,
    tag: str | None = None,
    git_url: str = BASILISK_GIT_URL,
    codegen: bool = False,
) -> str:
    """Return one synchronized local-path or tagged Git dependency."""
    if (path is None) == (tag is None):
        raise ValueError("Specify exactly one of path or tag")

    fields = [f'version = "={support_version}"']
    if path is not None:
        fields.append(f"path = {_toml_string(path)}")
    else:
        fields.extend(
            [
                f'git = "{git_url}"',
                f'tag = "{tag}"',
            ]
        )
    if codegen:
        fields.extend(
            [
                "default-features = false",
                'features = ["codegen"]',
            ]
        )
    return "{ " + ", ".join(fields) + " }"


def _toml_string(value: Path) -> str:
    """Return a cross-platform TOML path string."""
    path = value.resolve() if value.is_absolute() else value
    return json.dumps(path.as_posix())


def _cargo_dependency_path(
    sdk_repo_root: Path,
    basilisk_root: Path,
    crate_path: Path,
    manifest: Path,
) -> Path:
    """Use portable relative paths for the SDK's default Basilisk checkout."""
    default_basilisk = sdk_repo_root / "external" / "basilisk"
    if basilisk_root.resolve() == default_basilisk.resolve():
        return Path(os.path.relpath(crate_path, manifest.parent))
    return crate_path.resolve()


def sync_example_versions(
    sdk_repo_root: Path,
    versions: dict[str, str],
    bsk_version: str,
    basilisk_root: Path,
) -> None:
    """Align the copyable Rust extension manifests with synchronized BSK."""
    workspace = sdk_repo_root / "examples" / "custom-atm-extension" / "Cargo.toml"
    module = workspace.parent / "rustAtmosphere" / "Cargo.toml"
    if not workspace.is_file() or not module.is_file():
        raise FileNotFoundError(
            "The custom-atmosphere Rust example manifests are missing"
        )

    minimum = versions["BSK_RUST_MIN_VERSION"]
    support = versions["BSK_RUST_SUPPORT_CRATE_VERSION"]
    release_tag = f"v{bsk_version}" if is_publishable_bsk_version(bsk_version) else None
    crate_root = basilisk_root / "src" / "architecture" / "rust"
    crate_paths = {
        "bsk-build": crate_root / "bsk_build",
        "bsk-messages": crate_root / "bsk_messages",
    }
    if release_tag is None:
        missing = [
            path for path in crate_paths.values() if not (path / "Cargo.toml").is_file()
        ]
        if missing:
            missing_text = "\n".join(f"  - {path}" for path in missing)
            raise FileNotFoundError(
                "The selected Basilisk checkout lacks Rust support crates:\n"
                f"{missing_text}"
            )

    def dependency_specification(
        dependency: str, manifest: Path, *, codegen: bool = False
    ) -> str:
        if release_tag is not None:
            return _dependency_specification(
                support, tag=release_tag, codegen=codegen
            )
        return _dependency_specification(
            support,
            path=_cargo_dependency_path(
                sdk_repo_root,
                basilisk_root,
                crate_paths[dependency],
                manifest,
            ),
            codegen=codegen,
        )

    _replace_one(
        workspace,
        r'(^rust-version\s*=\s*")[^"]+("\s*$)',
        rf'\g<1>{minimum}\g<2>',
        "workspace Rust minimum version",
    )
    for dependency in ("bsk-build", "bsk-messages"):
        _replace_dependency(
            workspace,
            "[workspace.dependencies]",
            dependency,
            dependency_specification(dependency, workspace),
        )
    _replace_dependency(
        module,
        "[build-dependencies]",
        "bsk-build",
        dependency_specification("bsk-build", module, codegen=True),
    )
    if release_tag is not None:
        print(f"[bsk-sdk] Rust dependencies pinned to {release_tag}")
    else:
        print(f"[bsk-sdk] Rust dependencies use local checkout: {basilisk_root}")


def sync_rust_support(basilisk_root: Path, sdk_rust_root: Path = SDK_RUST_ROOT) -> int:
    """Replace ``sdk_rust_root`` with Rust support copied from Basilisk."""
    cmake_root = basilisk_root / "src" / "cmake"
    reset_dir(sdk_rust_root)
    copied = 0
    for filename in RUST_CMAKE_FILES:
        source = cmake_root / filename
        if not source.is_file():
            raise FileNotFoundError(
                f"Missing Basilisk Rust CMake support file: {source}"
            )
        copy_file(source, sdk_rust_root / "cmake" / filename)
        copied += 1

    source_root = basilisk_root / "src"
    for source_relative, destination_relative in RUST_LICENSE_FILES:
        source = source_root / source_relative
        if not source.is_file():
            raise FileNotFoundError(
                f"Missing Basilisk Rust license support file: {source}"
            )
        copy_file(source, sdk_rust_root / destination_relative)
        copied += 1

    _write_support_metadata(sdk_rust_root)

    return copied


def main(arguments: Sequence[str] | None = None) -> None:
    """Parse arguments and synchronize the core-owned Rust integration files."""
    parser = argparse.ArgumentParser(
        description="Sync Basilisk Rust build support into bsk-sdk"
    )
    parser.add_argument(
        "--basilisk-root",
        default=None,
        help="Path to Basilisk repository root (or set BSK_BASILISK_ROOT).",
    )
    parser.add_argument(
        "--skip-example-updates",
        action="store_true",
        help="Copy installed Rust support without modifying repository examples.",
    )
    options = parser.parse_args(arguments)

    basilisk_root = resolve_basilisk_root(options.basilisk_root)
    version_file = basilisk_root / BASILISK_VERSION_FILE
    if not version_file.is_file():
        raise FileNotFoundError(f"Missing Basilisk version file: {version_file}")
    bsk_version = version_file.read_text(encoding="utf-8").strip()
    copied = sync_rust_support(basilisk_root)
    versions = json.loads(
        (SDK_RUST_ROOT / SUPPORT_VERSIONS_FILE).read_text(encoding="utf-8")
    )
    if not options.skip_example_updates:
        sync_example_versions(SDK_REPO_ROOT, versions, bsk_version, basilisk_root)
    print(f"[bsk-sdk] Rust support synchronization complete ({copied} files).")


if __name__ == "__main__":
    main()
