#!/usr/bin/env python3

#
#  ISC License
#
#  Copyright (c) 2026, Autonomous Vehicle Systems Lab, University of Colorado at Boulder
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

"""Generate built-in Basilisk C message interface sources for the SDK.

Basilisk C modules include generated wrappers as:

    #include "cMsgCInterface/SomeMsg_C.h"

The SDK ships these generated headers and definitions so external plugin C
modules can use the same include paths without adding message-specific CMake.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _sync_paths import (  # noqa: E402
    SDK_REPO_ROOT,
    resolve_basilisk_root,
    resolve_basilisk_src_root,
)
from common import reset_dir  # noqa: E402

SDK_C_MSG_INTERFACE_ROOT = (
    SDK_REPO_ROOT / "src" / "bsk_sdk" / "include" / "cMsgCInterface"
)

def render_template(template: str, replacements: dict[str, str]) -> str:
    rendered = template
    for key, value in replacements.items():
        rendered = rendered.replace(f"@{key}@", value)
    return rendered


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate Basilisk built-in C message interfaces into bsk-sdk"
    )
    ap.add_argument(
        "--basilisk-root",
        default=None,
        help="Path to Basilisk repository root (or set BSK_BASILISK_ROOT).",
    )
    args = ap.parse_args()

    basilisk_root = resolve_basilisk_root(args.basilisk_root)
    src_root = resolve_basilisk_src_root(args.basilisk_root)
    payload_root = src_root / "architecture" / "msgPayloadDefC"
    template_root = src_root / "architecture" / "messaging" / "cMsgCInterface"

    header_template_path = template_root / "msg_C.h.in"
    source_template_path = template_root / "msg_C.cpp.in"
    if not header_template_path.exists() or not source_template_path.exists():
        raise FileNotFoundError(
            "Missing Basilisk C message interface templates under "
            f"{template_root}"
        )
    if not payload_root.is_dir():
        raise FileNotFoundError(f"Missing C message payload directory: {payload_root}")

    license_path = basilisk_root / "LICENSE"
    license_text = (
        license_path.read_text(encoding="utf-8").strip()
        if license_path.exists()
        else "Generated by bsk-sdk. See the Basilisk ISC License."
    )
    header_template = header_template_path.read_text(encoding="utf-8")
    source_template = source_template_path.read_text(encoding="utf-8")

    reset_dir(SDK_C_MSG_INTERFACE_ROOT)

    generated = 0
    for payload in sorted(payload_root.glob("*Payload.h")):
        msg_name = payload.stem
        if not msg_name.endswith("Payload"):
            continue
        msg_type = msg_name[: -len("Payload")]
        replacements = {
            "MSG_AUTOSOURCE_LICENSE": license_text,
            "MSG_AUTOSOURCE_TYPE": msg_type,
            "MSG_AUTOSOURCE_HEADER": f"architecture/msgPayloadDefC/{payload.name}",
        }

        header_out = SDK_C_MSG_INTERFACE_ROOT / f"{msg_type}_C.h"
        source_out = SDK_C_MSG_INTERFACE_ROOT / f"{msg_type}_C.cpp"
        header_out.write_text(
            render_template(header_template, replacements),
            encoding="utf-8",
        )
        source_out.write_text(
            render_template(source_template, replacements),
            encoding="utf-8",
        )
        generated += 1

    print(
        "[bsk-sdk] Generated built-in C message interfaces "
        f"({generated} messages, {generated * 2} files)."
    )


if __name__ == "__main__":
    main()
